version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - data_init
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supply_chain_ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - API_URL=http://backend:8000
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      backend:
        condition: service_healthy

  data_init:
    image: python:3.9-slim
    container_name: supply_chain_data_init
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             python -c 'from src.utils import generate_synthetic_sales_data, generate_synthetic_locations;
                        generate_synthetic_sales_data();
                        generate_synthetic_locations()'"
